### ISSUE TITLE
Details about crypt. hashing

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#113]
I was reading the docs and couldn't understand how this works. Is there a single function that generates the cryptographic hashing, or is it code repeated in all of them?

* If it's only one, then please put the details below in the documentation of that function. I excluded it from the package description (and put it into import.q.sorts) since it is too much detail for something minor.

* If it is code repeated, consider creating a function for this (good coding practice), where you can also put all the details about hashing pros & cons.

Alternatively, if you just say automatic cryptographic IDs, then I think that further details are not needed (It was the 'hashed' vs 'handle' and 'hashed ID' what was very confusing all together, but simply saying 'automatic ID' or 'ID' seems understandable enough for anyone without further detail.)

```" In that case, IDs are computed by “summarizing” the complete item wordings ("Q Method is used by a crazy, but charming community of ...") into a hexadecimal number ("ae128fs"), a process known as cryptographic hashing. These hash values change whenever anything in the full item wordings is changed, and allow a precise identification of different versions of an item. This function never exposes users to the hash values; the encrypting and decrypting are done under the hood by the respective functions. Automatic, hashed IDs are generally recommended and easier to use, but some caveats apply (see make.cards)."```

**Comment by aiorazabala** [comment]
@maxheld83

**Comment by maxheld83** [comment]
**re: in which functions does the (de-)hashing happen?**

The hashing happens in three functions `make.cards()`, `import.q.sorts()` and `import.q.feedback()`.

The function itself is trivial, taken from the digest package. 
It's just this:

```
digest("This is the item text", algo="crc32", serialize = FALSE)
[1] "14f238fc"
```

In the above functions, this hashing is just implemented as an `apply()` function.
I wouldn't think it's necessary to put this into a separate function, it's just so straightforward.

Does that make sense @aiorazabala ?

The point of putting this hashing *inside* these functions would also be that the user is never actually exposed to any object with these hashed IDs – I think that might only make things more complicated.

**Comment by maxheld83** [comment]
I would suggest to go over the the documentation again, and kill most references to "hashing".

I think the word hashing *should* stay in the documentation though, because it's a very particular kind of operation.
I really wanted users to understand that it is *not* possible to extract the complete item wording from the hash, absent the full list of what these items could be. (Hence the emphasis on storing the exact version of full item wordings and taking backup precautions).

**Comment by maxheld83** [comment]
I just added a little pointer to the `digest()` package, from which the hashing comes, so people can read up on details there.

**Comment by maxheld83** [comment]
I've added the following sentence to the functions that do the hashing:

> The automatic summary of full item wordings, technically known as \emph{hashing}, proceeds internally by passing the full item wording to the \code{digest()} function of the package \pkg{digest} (with \code{algo=crc32, serialize=FALSE}.)

**Comment by maxheld83** [comment]
on second thought, I think the reference to hashes *should* stay in the documentation wherever possible, and not only the "dumbed down" *automatic* description.
I understand that some people might be put off by the concept of hashes, but those people should probably *not* use this (optional!) function anyway, because it *can* be tricky (it becomes tricky if people don't take a precise snapshot of their full item wordings – that's about the only tricky scenario, actually).

I also think that *automatic* as the sole description might be misleading, because users might still expect some kind of object somewhere, where they can look at the automatic IDs. 
The whole point of hashed IDs, is, of course, that they need not ever be stored or returned, because they can always be re-constructed *on the fly* from the full item wordings.

Does that make sense?

**Comment by maxheld83** [comment]
I'm really quite confident that this works, and is appropriately documented – I think @VerenaKasztantowicz has used the automatic/hashed IDs already.

If it's still unclear, please have a look at the respective section in `qmethod-package.Rd` --- I hope it's pretty clear what the option does.

**Comment by aiorazabala** [comment]
Cool
