### ISSUE TITLE
column naming conventions

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#132]
Dataframes in `results` from `qmethod()` often have column names such as `zsc_n_f1` or something similar by default.
However, when they are being renamed by `q.fnames()` (via #69), they are only called `foo`, not ~~`zsc_n_foo`~~.

I actually prefer the latter, because the `zsc_n`-part (etc.) is already contained in the object name `results$zsc_n`, so I was wondering whether we might (at some point) streamline this (maybe also as per #131 ).

The downside would be that users might confuse one output dataframe from another, obviously (I guess that was the rationale for the verbose colnames in the first place).

**Comment by maxheld83** [comment]
For `q.item.sd` and other additional functions, I'm sticking with the status quo of verbose colnames (unless there *are* fnames).

**Comment by aiorazabala** [comment]
The advantage of having full names for the columns is that, when summarising or extracting results (individual columns) and putting them together in new frames, they still indicate what data they contain. 

e.g. if one makes a single table with z-scores and factor scores (such as for publication of results), if there wasn't a verbose name one would lose sight of what each column indicates. I'd keep these as they are, in order to avoid confusion.
