### ISSUE TITLE
Package updates in CRAN

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#19]
In this issue, I'll register every time that the package is updated in CRAN repositories.

**Comment by maxheld83** [comment]
thanks that's really neat @aiorazabala !

Would you consider using github's build in releases function for this (as I also suggest in #38)?
It's a really lightweight function, it essentially just marks some point in history as a "release", allows some release notes and some upload space for binaries.

Obviously, the *actual* release still (sadly?) happens manually over CRAN, but parallel releases on here would provide a convenient way to mark the releases to CRAN.

(Github releases are actually git tags, so they are available within git).

anyway, obviously, I have a slight [OCD](https://en.wikipedia.org/wiki/Obsessive–compulsive_disorder)-problem with meta-stuff :smiley: ...

**Comment by aiorazabala** [comment]
where/ how does that function work?

**Comment by maxheld83** [comment]
uh sorry, I should have added that. Docs are [here](https://help.github.com/articles/creating-releases/)

It's really quite minimal, and there's not much to be done since absolutely most people (for now) will get their qmethod from CRAN.

Advantage is that releases are *tags*, which are git-artifacts, so you can quickly say something like: *show me whatever we changed since the last CRAN release* or whatever.

Ps.: I also hear (as in #35) that some influential R devs are thinking about replacing/complementing CRAN with some git(hub)/releases setup, as most active development is on git(hub) anyway.

**Comment by maxheld83** [comment]
I guess we can close this, now that there are releases for CRAN updates, right?
