### ISSUE TITLE
check that existing plots, functions work with centroid-extracted data

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#226]
this might be completely unproblematic, though I've grown a little weary of treating different factor extraction results equally.
PCA, in particular, is quite "undemanding" (currently implemented), and it is possible that there are things that cannot be done in the same way (or not at all) with centroid-extracted data.

Just of the top of my head, I'm wondering whether centroid produces a pattern _and_ a structure matrix (the two are the same in PCA with orthogonal rotation, also see #95).

Anyway, would be nice to make sure about these things.

In case there are hiccups, that's not necessarily a problem, we should just make sure we document apparent incompatibilities, and warn about and/or disallow such user choices.

**Comment by jfou** [comment]
Hello Max,

Perhaps unsurprisingly, I'm also interested in learning about any updates to the centroid implementation in the qmethod package.

Thanks again,
Jeremy

**Comment by maxheld83** [comment]
this (#15) is very high up on my agenda for Q dev, because so many people find it very important (though I personally remain quite sceptical about it).

Not sure what @aiorazabala's thinking is.

**Comment by maxheld83** [comment]
incidentally @jfou *who are you*? :) your profile doesn't seem to say much ...

**Comment by jfou** [comment]
Thank you so much for your response, Max. 

Implementing centroid to illustrate it doesn't make much sense? There are worse goals! I don't claim to understand the statistical underpinnings of it, either. I just know it is a favorite of the original Q practitioners, and I'm trying to compare results. It is telling, maybe, that SPSS doesn't include it as a rotation option...unless it's one of the many maddening examples of a lack of naming standards (at least in English).

PCA seems to be more well-rounded, though, so I'm not going to attempt to convince you (or anyone). Andy Field (my SPSS guru) certainly favors it, for what it's worth.

As for me, I'm not anybody. Just a cultural researcher trying to be diligent with q methodology. I did put a bit on my profile - though I rarely do on forums.

**Comment by bobbraswell** [comment]
Hi, friends. I currently have too many doctoral students depending on me to review their proposals to commit myself to work on this software at the moment. I deeply regret this because I understand it, I believe in the value of it, and I actually enjoy working with it. There's not much more to say, except to reassure Max (and others) that this is worth caring about.

PCA mathematically guarantees that variance is maximized at each step. If this were R, that would be about as much as we needed to know, as we would be primarily interested in variance. But this is not R.

Centroid mathematically guarantees that absolute values of loadings are maximized at each step. Loadings are actually more germane to Q than are variances, though of course the two usually go together. Where there is a difference, we actually care about the loadings.

PCA always overestimates variances by using ones on the diagonal, compared to a true factor analysis algorithm that uses communality estimates or other reduced diagonal entries. This makes almost no difference if only a few factors are extracted but can make a defining difference for later factors, should those be indicated. Since we normally extract them first and only afterward look at them to see if we should keep or interpret them, we are sometimes looking at misleading information based on inflated diagonals when making that decision.

For these two reasons, in the context of Q where we seek to maximize loadings but try to avoid making decisions based on inflated diagonal entries, when the results of PCA and Centroid are compared, it should be with an eye to judging how good an estimate the PCA makes of the Centroid answer and not the other way around. PCA is a ubiquitous, useful, robust estimate of the properly implemented Centroid solution, which is the gold standard for Q.

It is the issue of proper implementation that is a bit of a sticking point. Most software implementations I have tested have occasional problems. Since the absolute value of a difference is actually harder to work with in software than a squared difference, even though centroid is conceptually easier than PCA, it is surprisingly tricky to implement in a way that robustly handles all the weird things that can happen when extracting the later factors from a matrix of near-zero residuals. My initial routine became buggy when extracting late factors with some data sets, and I haven't had time to dig into why. I suspect with near-zero entries, a tiny negative value can become a positive value due to even a small rounding error and send the algorithm off in a direction that was unexpected. That is just an educated guess, I haven't had time to debug it. 

Thanks for reading. Thanks, Max, for the mention and your keen mind and energy applied to Q. Thanks for keeping this issue alive, though I don't have time to help you with that at the moment.

**Comment by maxheld83** [comment]
thanks so much for the thoughtful comment, @bobbraswell – though the praise should go to @aiorazabala who's done absolutely most of the work here.

I'll take your notes as another motivation to dig down into Centroid if I get a chance @bobbraswell – I *really* do want to understand it fully, before criticising it. Admittedly, I currently don't.

I am not sure about the diagonal matter, but that might be solved once I get to work. It always seems to me that actually, ones on the diagonal *are* adequate for Q (as in PCA), because we do not have a latent variable model (or do we?!). This is very philosophical, I'm just beginning to figure this out.

**Comment by jfou** [comment]
Many thanks, @bobbraswell. for the explanation! And @maxheld83 and @aiorazabala , whenever you can turn to it, great! It may not be in time for my current project, but I have a feeling it will come in handy for me or someone else down the road.



Back

**Comment by aiorazabala** [comment]
Centroid code by Frans Hermans integrated seamlessly.
