### ISSUE TITLE
validate centroid extraction vis-a-vis PQMethod

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#227]
before releasing, we should validate centroid extraction (#15) against `PQMethod` by Peter Schmolck, which _does_ offer centroid extraction already, so the same centroid extraction of, say, the `lipset` data should yield the same loadings.

Or does this not work because of the "indeterminacy" of centroid and/or manual reflection?

**Comment by maxheld83** [comment]
@aiorazabala has already done this very thorough and demanding work for the base functions, as documented in her R Journal article (and has also implemented centroid in MS Excel some time back, if I remember correctly) – maybe she has some advice on how to proceed here?

**Comment by bobbraswell** [comment]
I just noticed what must be a bug in the centroid routine. Yes, it should match PQMethod results, but it won't until the bug is squashed. I just noticed the eigenvalues are incorrect, and I don't know yet if there's a glitch in the way they are reported or if it's a deeper problem. I was getting good results at one time but made several changes to clean up the code, must have broken something.

**Comment by aiorazabala** [comment]
Done
