### ISSUE TITLE
implement & document INTERACTIVE + MANUAL reflection

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#228]
My understanding of, and experience _with_ centroid extraction (as per #15) is limited, so I apologize in advance if this is nonsensical:

I understand that much of the appeal of centroid extraction lies in being able to _manually_ reflect columns in the residuals matrix, a process that should ideally be guided (if I understand correctly) by some kind of _substantive understanding_ by the researcher, and will likely be an _iterative_ process.

I find this quite fascinating, and have tried to implement something similar in `q.rotate()` in #13.

I think it would be great if we could offer something similar in Centroid extraction, though I've always struggled to understand just how such a user interface should look like, and what kind of information might guide manual reflections.

I also think it might be good to _store_ the order of manual rotations in the results object of `qmethod()`, just for reproducibility and testing (might also make #227 a lot easier :smile: ).

Curious what your thoughts are on this @aiorazabala and @bobbraswell, since you both have more experience with actually implementing / running centroid.

**Comment by bobbraswell** [comment]
Re: "I understand that much of the appeal of centroid extraction lies in being able to manually reflect columns in the residuals matrix, a process that should ideally be guided (if I understand correctly) by some kind of substantive understanding by the researcher, and will likely be an iterative process."

I think you may have overgeneralized something Peter Schmolck was saying about William Stephenson in particular when you formed this impression. Peter imagines WS enjoying the reflection of matrix columns the way some people enjoy sudoku, but there is no substantive content in view at this stage, it is all just playing with numbers.  I have played with this (and it can be fun) but I see no reason to incorporate a manual version in R. Those who want to play this game are better advised to use a spreadsheet, and those few will have no trouble building their own.

Since combinations of small negative values in a matrix may or may not outweigh larger negative values depending on reflections chosen, some of the algorithms used can be subject to local maxima. This is what Peter raised as an alternative definition of indeterminacy. I think he is right in saying that different extractions that might result from this are just rotations of each other, so for a matrix that will subsequently be rotated it is not much of an issue. There are many new applications of centroid extraction because of its advantages over PCA, and where the unrotated factors are at issue, this becomes more of a question. Just as PCA provably maximizes variance at each step, centroid provably maximizes loadings, IF the reflections are done optimally. Finding a monotonic algorithm that always finds the best combination of reflections is a solved problem but it is a fairly recent development. You might be interested in http://www4.ncsu.edu/~mtchu/Research/Papers/centroid.pdf .

**Comment by aiorazabala** [comment]
Not needed
