### ISSUE TITLE
make qmethod cookbook

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#24]
@aiorazabala mentioned she was building a qmethod cookbook for non-R users and/or q newbies.

**Comment by maxheld83** [comment]
would you like me to add some documentation / tips on the import and printing stuff that I did in #36 @aiorazabala ?
That might also solve the need for a documentation on the file structure required by these functions.

I would also add some words on why git versioning for these things (especially the concourse and item sample) makes sense.
Not sure what the context of your class is, though.

A practical limitation of the git wikis is that while they are full repositories, that can be cloned and edited offline, they don't offer pull requests.
So I can add my edits either in a new branch (only the `master` branch is shown online), or edit directly in yours.

**Comment by aiorazabala** [comment]
Please feel free to add it to the cookbook.

Information that is essential to use the new functions should go directly in the documentation of the function (man/*.Rd files), section 'Arguments' or 'Details'.

Information that you'd like to use to further illustrate the function can go in the cookbook. 

For organisation, please add it as a new page, to be linked from the current cookbook---I intend to write the cookbook, rather than as a very long single page, as a page where all non-essential steps have a link to another page, e.g. the first step will be "Have you installed R and qmethod? --if not, go to xxx page"

**Comment by maxheld83** [comment]
I'll do that, thanks for the heads up.

All the *necessary* documentation should be in `/man/` already as per pull request #36

**Comment by aiorazabala** [comment]
The cookbook for the analysis is more or less complete now, subject to bug fixing and improvements.
