### ISSUE TITLE
add original validation as automatic test

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#262]
@aiorazabala ([Zabala 2014](http://journal.r-project.org/archive/2014-2/zabala.pdf)) has extensively validated `qmethod` using different datasets and configurations vis-a-vis PQMethod.

It would be nice to take these de-facto tests that were already written and make them into formal `testthat()` tests, as part of #259 

@aiorazabala do you by any chance still have some supporting material and/or data for this original validation?

**Comment by maxheld83** [comment]
@aiorazabala just send part of the data

**Comment by aiorazabala** [comment]
Just sent all the remaining files I could find

**Comment by aiorazabala** [comment]
The files for testing against PQmethod from 2014 are there but prefer not to include within the package because they're untidy, and unlikely to run in other computers (e.g. path naming etc.; not a priority to clean up).
Also files for testing updated versions against qmethod v.1.2.4 (to be made available at some point), and files for testing centroid against PQmethod (2021)
All available upon request.
