### ISSUE TITLE
try out and adapt functions for very large P-sets

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#288]
Job van Exel might give me his 14xx P-set dataset soon, and I'd be nice to make sure that all the functions work and plots make sense (some will not) for such a large P-set, before he tries it himself.

**Comment by aiorazabala** [comment]
Some notes about using Q method with large P-sets (220 Q-sorts):
- No consensus statements were found, this might be because the threshold to determine dist & cons depends mostly upon the number of flagged Q-sorts, and this number is high when the P-set is high. This may require setting a higher threshold in the equation, or finding alternative ways of comparing the statements across factors
- For the plot functions, in sum, those functions that plot Q-sorts work fine, but the result is quite cluttered. This is obvious, and can't think of any solution straight away (perhaps ), so we may leave it as it is.
 - function `q.compplot` and `q.rotplot` work*, but because there are so many Q-sorts, it's quite cluttered (though  I can't think of a solution right away)
 - ibid. for function `q.corrplot`--- @maxheld83 What's the difference between this function and any other correlogram function? (if there isn't any, then we shouldn't include it in the package)
 - `q.loaplot()` maybe use alternative ways of scatterplots for large datasets? eg http://vis.supstat.com/2012/11/to-see-a-world-in-grains-of-sand/
 - `q.scoreplot` (my favourite!) works as well. however with many factors, the 'pyramids' are collapsed.

*They work with 3 factors extracted, but with 6 they give an error `Error: Results must be all atomic, or all data frames`
