### ISSUE TITLE
Online demo: add feature to upload your own data

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#42]
There is an online demo of the package, currently only with 'Lipset' data: https://azabala.shinyapps.io/shinyapps/qmethod.Rmd
This is build with `shiny` package.

In shiny, there are also snippets to 'upload files' (http://shiny.rstudio.com/reference/shiny/latest/ )

Add such feature, so that anyone can upload their LIS, TXT or CSV files and run the analysis on the browser.

**Comment by maxheld83** [comment]
This is a great idea, and it would really drive adoption forward, I think.
Thanks so much for hacking this together so quickly!
Maybe we should wait with another q-list announcement until we also have other extraction methods (#15, #20), too – just to avoid controversy.

**Comment by maxheld83** [comment]
Also, on the substantive thing of adding this functionality:
I am not sure how far @aiorazabala has come with this (maybe it's done already, in which case forget what I'm about to say).
As I mentioned in #32, I see a strong medium-term need to really systematize the way all q data (concourse, qset, pset, qsorts etc.) are entered and version controlled.
I think that much of the current practice here is too ad-hoc.
For example, I've yet to see a q study that uses someone elses concourse and/or qset, or to systematically iterate over and test/re-test a given set of items – all of which are things that *would* be  expected from a research method.

This is a long way of saying: file structure and versioning matters. 
I'll write down a suggestion as to how to do this (as in #32 ) soon.

What does this have to do with the web UI + shiny?
I think it would be great if the web UI automatically asked for, and created the same kind of data structures (maybe even including (git) versioning) as in #32, so that even when people just do their analyses online (as, I think, eventually, many will do), they can plug into a good structure.

I'd like to look into how to do this in shiny, but that would take a while, so it's probably best to start with some simple upload.

**Comment by aiorazabala** [comment]
Yep, start with simple will be most user friendly.

Indeed, a Q study can be as simple as a two-way matrix with Q-sorts and items, plus a vector of what each item means, i.e. the statements. In that case, version control and a standard folder structure might be an unnecessary complication.

**Comment by maxheld83** [comment]
absolutely agreed.
Thanks for the reminder, that not *every* q study needs `git submodules` :smirk: (though I think more than we think *do* need it).

I've added the shiny+git(hub) addition in #48, though I probably won't get to working on that anytime soon.
One advantage of integrating with git(hub) might be that you then don't need access to the local file system from shiny at all, because it's all done on git(hub), which already offers a web interface.

**Comment by aiorazabala** [comment]
The upload feature is now added. Can we close this issue now @maxheld83 ?

**Comment by maxheld83** [comment]
fantastic. yes!
In the long run, I'd like to add a feature to link a git(hub) repository, which should be possible via github API or something as per #48, but that's later.
