### ISSUE TITLE
disallow or warn about oblique rotation methods? (pattern matrix != structure matrix)

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#95]
Peter Schmolck just reported this concern on the qmethod e-mail list:

> I'm not sure also that everything is methodologically sound throughout. For instance, in case of oblimin rotation one must differentiate between pattern and structure matrices instead of only one factor loading matrix as in varimax. The output does not tell which matrix is displayed, and I'm not so sure if it is quite clear how one should apply the Spearman-formula for factor weights (which is quite unknown outside of Q) to oblique pattern or structure coefficients.

**Comment by maxheld83** [comment]
I have no idea about this, just thought we should track this concern here.

**Comment by maxheld83** [comment]
I *could* be wrong, but I believe this *only* applies to non-PCA extraction methods, which we currently do not offer.
I believe that in PCA (with orthogonal rotation?), pattern and structure matrices are the same.

**Comment by maxheld83** [comment]
this seems relevant, underscoring what Peter Schmolck said:

> In other words, whenever the factors are perfectly uncorrelated the pattern coefficients are also structure coefficients (and therefore must fall within the range -1 to +1), and in this case are more appropriately termed pattern/structure coefficients. And when factors are first extracted, the factors are always perfectly uncorrelated.
> –– Thompson 2004: 19

**Comment by maxheld83** [comment]
so I'm not sure about this.
It might be that even under PCA, structure and pattern matrices diverge, if non-orthogonal rotation methods such as `oblimin` are used.

The problem *might* be that `qmethod()` currently *allows* for non-orthogonal rotation methods, but produces only a `loa`, and it might not be clear whether this is the pattern or structure matrix or which one of them would be appropriate.

I'm out of my wits here, might be totally wrong.

We might want to get back to Peter Schmolck about this.

One preliminary fix might be to issue a simple warning, or to disallow oblique methods for now.

Could you have a look at this, if this *is* in fact a valid concern @aiorazabala ?

**Comment by maxheld83** [comment]
the more I look into this, the more perplexed I am by the oblique rotations.

I'm not sure we're currently set up to use oblique rotations properly; especially considering the difference between the pattern and structure matrices.

Also, kicking out oblique rotations would make the code a lot cleaner for now :), especially for stuff like #171 

I might be wrong (I often am), but I wonder whether truly allowing oblique rotations would not require quite a substantial patch to qmethod, probably with a release focused just on that and all its implications.

**Comment by aiorazabala** [comment]
Aiora to add warning "at your own risk"

**Comment by jfou** [comment]
Hello All!
While I'm not new to stats, I'm new to R and qmethod. Mostly, I use SPSS. But the capabilities you've been working on here would make things far easier for my cultural research. I'm very appreciative of your work thus far!

To the point: I'm wondering:

1. Where are your current thoughts on the oblimin rotation implementation in qmethod?  I still see it as an option both in the beta online version and the R package.

2. If oblimin is still safe to use in qmethod, then what is the assumed delta used? 0?  

3. The lack of structure and pattern matrices is confusing to me, as that is what I'm used to seeing in SPSS. 

My statements/items are likely correlated, so oblique rotation is a must (which is why I moved away from pqmethod). 

Any assistance or updates you can provide would be most helpful!

Many thanks,
Jeremy

**Comment by maxheld83** [comment]
Hi @jfou, great to see that you're interested in @aiorazabala 's package. I'll have to defer to Aiora, because I haven't been active in the last couple of months (now have a new job and muuch more time for Q going forward, so I should be be back soon).

re: oblique: My understanding is that currently qmethod is unable to safely use oblique rotations, because, if nothing else, the package only has one loadings matrix, which is fine in PCA + orthogonal rotations, where because structure == pattern matrix.

I'm also personally still struggling on a conceptual level as to what exactly an oblique rotation method *means* in Q terms.

For now, I am concentrated on orthogonal rotation methods, where I'm still working on some comparisons (varimax vs equamax vs quartimax), as well as – potentially – a custom Q rotation method. (For varimax vs other orthogonal methods, also see [Noori Akthar-Danesh](http://fhs.mcmaster.ca/ceb/faculty_member_akhtar-danesh.htm) forthcoming piece).

**Comment by jfou** [comment]
What I'm struggling with is that there isn't a program that does both Centroid extractions and oblique rotations. Maybe I'm missing something, though! With correlations assured between factors - at least in my case - oblimin seems to be the way to best unearth whatever the data are trying to tell me. One would think that an psychological construct from the data would be correlated with some other psychological construct, too. So if they aren't independent, I'm not sure why we use orthogonal rotations in Q, generally.

**Comment by aiorazabala** [comment]
Hi Jeremy @jfou ,
Thanks a lot for your input. Here my only contribution is that of the programmer, i.e. oblimin is a choice in the rotation method in qmethod() because this rotation is available in the principal components' packages used by the qmethod pkg (pkg psych), but that doesn't mean that it's appropriate or inappropriate in Q.

As far as I know, this is the first time that such rotation is usable in Q analysis and so a comparison of the impact of mathematical rotation methods on Q results is a rather completely new avenue for research.

In line with Noori's paper, a suggestion would be to do a sensitivity analysis to compare to what extent the choice of rotation methods affects the results, and in which empirical cases one rotation may be preferable to others. In an initial exploration using [the GUI](https://github.com/aiorazabala/qmethod/wiki/Graphical-user-interface-for-qmethod-(beta)), I could see that the results could change importantly (e.g. by looking at the correlations between factors, or at the spread of z-scores in the plot), even when retaining the same number of factors. 

As @maxheld83 , I won't work on methodology or major package additions in the near future (only in actual Q studies! :) ), so it'd be great if you'd like to take the lead in such a study!

**Comment by jfou** [comment]
Good to hear from you Aiora @aiorazabala !

After I finish the analysis and report, I would love to run the sensitivity analysis - comparing methods for best fit is one of the reasons I'm looking at this issue at all.

First, however, I need to finish my current (and pressing!) project, and there is a programming element that you @aiorazabala might be able to help with. Is there a way to manually import a Centroid extraction into qmethod? One of the things I'm trying to compare is PCA vs. Centroid, and as I've said, I've not found a way to do an apples to apples comparison. 

For example, I feel like I'm close to getting SPSS to load the Centroid extraction instead of PCA. SPSS has the oblimin rotation option. 

Another interesting (and potentially concerning) element is that I'm getting different results with qmethod and SPSS when running a PCA extraction and oblimin rotation. The rotated loadings are different since in qmethod there aren't structure or pattern loading tables - and there should be for oblique rotations like oblimin. (this concern was echoed by @maxheld83). This leads me to thing that while oblmin is technically available, something is off in its implementation in the psych pkg. Are we off base? Or maybe I'm missing something?

Many thanks,
Jeremy

**Comment by aiorazabala** [comment]
Hi Jeremy, for comparison between centroid and PCA in R, at the moment I can only think of importing results from PQmethod-centroid into R in a systematic way (someone released recently an app that exports PQmethod results into tables directly. Or otherwise program the centroid in R yourself (I did it in Excel like five years ago, it shouldn't be too complicated).

As for the oblimin rotation, one should check its implementation with the documentation of 'psych', since 'qmethod' just wraps what 'psych' is doing.
If you'd like to extract the full info reported by the function wrapped from 'psych', you can use directly the raw code that implements it in 'qmethod'. In the code of the function 'qmethod', lines 27 & 28:
```{r}
cor.data <- cor(dataset, method = cor.method) 
# where dataset is your two-way matrix of Q-sorts,
# and cor.method is "pearson" (to keep things equal to PQmethod)
loa <- as.data.frame(unclass(principal(cor.data, 
                                       nfactors = nfactors, 
                                       rotate = rotation, ...)$loadings))
```
or simply explore the full object resulting from:
```{r}
loa <- principal(dataset, nfactors=nfactors, rotate=rotation)
```

What do you mean with 'off base'?
Best wishes, 
PS: for prompt response, please email me (aiora.zabala at gmail)

**Comment by aiorazabala** [comment]
Warning added when users select rotations other than 'varimax'.
For more on this topic, see 2017 Akhtar-Danesh "A comparison between major factor extraction and factor rotation techniques in Q-methodology" Open Journal of Applied Sciences 7 (04), 147 https://www.scirp.org/html/4-2310716_75813.htm
